services:
  ui:
    container_name: traffic_ai_ui 
    build: ./server/
    ports:
      - 80:80
    volumes:
      - applicationdata:/usr/share/nginx/html/applicationdata
    links:
      - "core:ai"
  core:
    container_name: traffic_ai_core
    build: ./classifier/
    command: bash script.sh
    volumes:
      - applicationdata:/classifier/applicationdata

volumes:
  applicationdata: