version: "3.7"

services:

  client:
    container_name: traffic_ai_ui 
    build: ./client/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - applicationdata:/applicationdata
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER_CLIENT}
    depends_on:
      - server
  
  server:
    container_name: traffic_ai_core
    build: ./server/
    ports:
      - 9090:9090
    volumes:
      - applicationdata:/server/applicationdata
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER_SERVER}

volumes:
  applicationdata:
