services:
  ui:
    container_name: traffic_ai_ui 
    build: ./nodejs/
    ports:
      - 80:80
    volumes:
      - applicationdata:/usr/src/app/applicationdata
    links:
      - "core:ai"
  core:
    container_name: traffic_ai_core
    build: ./classifier/
    command: bash script.sh
    volumes:
      - applicationdata:/classifier/applicationdata

volumes:
  applicationdata: